# Generated by Django 6.0.5 on 2026-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_options_contact_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='request_type',
            field=models.CharField(choices=[('مشاوره رایگان', 'مشاوره رایگان'), ('درخواست پروژه', 'درخواست پروژه'), ('سایر موارد', 'سایر موارد')], max_length=50),
        ),
    ]
