# Generated by Django 6.0.5 on 2026-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contact_options_remove_contact_admin_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='request_type',
            field=models.CharField(choices=[('free_consultation', 'مشاوره رایگان'), ('project_request', 'درخواست پروژه'), ('other', 'سایر موارد')], max_length=50),
        ),
    ]
